version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest        
    image: rabbitmq:3-management
    
  customerapi:
    container_name: customerapi
    image: sample-microservices_customerapi:latest
    ports:
      - 5000:80
      - 5001:443
    restart: on-failure

  orderapi:
    container_name: orderapi
    image: sample-microservices_orderapi:latest
    ports:
      - 6000:80
      - 6001:443
    restart: on-failure