# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest        
    image: rabbitmq:3-management

  customerapi:
    image: customerapi
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
    ports:
        - 8000:80
        - 8001:443  
    restart: on-failure        
    depends_on:
        - rabbitmq