version: '3.4'

services:
  customerapi:
    container_name: customerapi
    build:
      context: ./CustomerApi
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    restart: on-failure

  orderapi:
    container_name: orderapi
    build:
      context: ./OrderApi
      dockerfile: Dockerfile
    ports:
      - 6000:80
      - 6001:443
    restart: on-failure