# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  customerapi:
    container_name: customerapi
    image: customerapi:latest
    ports:
      - 5000:80
      - 5001:443
    restart: on-failure

  orderapi:
    container_name: orderapi
    image: orderapi:latest
    ports:
      - 6000:80
      - 6001:443
    restart: on-failure